#!/bin/bash

# if file exists at /tmp/.chromatic.update 
if [ -f "/tmp/.chromatic.update" ]; then
    echo "[*] skipping uicache"
else
    echo "[*] rebuilding home screen..."
    uicache -p /Applications/chromatic.app
    echo "[*] completed"
fi