#!/bin/bash

ENV_PREFIX=""

APP_PATH="$ENV_PREFIX/Applications/chromatic.app"

if [ -d "$APP_PATH" ]; then
    chown -R root:wheel "$APP_PATH"
    chmod -R 755 "$APP_PATH"
    chmod +s "$APP_PATH/chromatic"
else
    echo "Malformed Package: Missing $APP_PATH"
fi

# env chromaticAuxiliaryExec is set
# then exit with 0
if [ -n "$chromaticAuxiliaryExec" ]; then
    exit 0
fi

echo "[*] reloading icon cache for springboard..."
uicache -p "$APP_PATH"
echo "[*] completed"